spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bokduck?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: "0000"
    driver-class-name: com.mysql.cj.jdbc.Driver
  
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: ssafy.bokduck.dto
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: v3ryS3cr3tK3yF0rJw7T0k3nGenera7ionAndValidat1onMustBeLon9Enough
  expiration: 86400000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs # 1 day

logging:
  level:
    ssafy.bokduck.mapper: DEBUG
    org.springframework.jdbc.core: DEBUG

llm:
  api-key: S14P02AG04-a85b76ca-d893-420e-b425-72c2d9d8fadb
  model: gemini-2.5-flash-lite
